### ISSUE TITLE
Archives Tab, thumbnails for the clips

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1036]
I think this doesn't need actual thumbnails, just show the player embedded.

Open for better ideas.

**Comment by muneeb2542** [comment]
@marcoherbst a player could be embedded but as the archive list would increase,the page would become really slow and at some point, it might become unresponsive due to many initializations of the player.

Plus we are requesting the clip from the timelapse server and we would have to create a thumbnail_url for it at the backend of it because jquery does not allow us to get a simple thumbnail from a video source.

So I'm leaving this for now.

**Comment by marcoherbst** [comment]
Let's close this. It makes more sense if we had a /users/archives page, but not for a /camera-id/archives
