### ISSUE TITLE
Missing client-side validation on add a camera page

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#1093]
The camera name is limited to 24 characters in the API, but there's no validation for it on the client side: https://github.com/evercam/evercam-dashboard/issues/1092

This most likely wasn't the only missing one.

**Comment by marcoherbst** [comment]
@affan00 what do you prefer? An error if the user fills in too many characters? Or, don't let them fill in too many characters?

**Comment by affan00** [comment]
I think second one is much better "don't let them fill in too many
characters".

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani

**Comment by azharmalik3** [comment]
@affan00 

Camera add page doesn't send POST request until complete form validation.
Display proper error message return from API instead of static one.

**Comment by muneeb2542** [comment]
I have fixed the underlying cause for the missing validations,this was happening due to mixpanel sending an unrequired request on each submit the forms,whether the form was validated or not.So I wrote some conditions for it and it will only happen now when the validations are ok.

Plus now the error messages displayed are exactly like the one we get in API.
So closing this.
