### ISSUE TITLE
Sign up Sign in pages to have full screen video playing in background like mobile app

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1130]
Affan, @liutingdu  will help you if you need.
My suggestion is to keep the white box, just play the video behind that.

Pay careful attention to optimisation and browser compatibility, that's the key to success in this task.

**Comment by liutingdu** [comment]
The fullscreen video on Android is in the welcome page (the first page after installing the app), not in sign in & sign up page.

To add it to sign in/sign up page, in order to make the user focus on the form, I agree it's necessary to keep the white box.

[Here](https://www.thetileapp.com/) is a nice example of how other people did it, the related code is:

```html
<video class="cover-image" style="width: 100%; height: auto;" autoplay="" loop="" preload="" poster="poster.jpg" id="loop-video">
   <source src="https://d3oqyucz5rc7jk.cloudfront.net/images/video-loop.mp4" type="video/mp4">
</video>
```

In Android I am using mp4 as well.

@affan00 Let me know if you need any information :)

**Comment by marcoherbst** [comment]
@affan00  closed?

(NB ... I notice  it doesn't play on iPad .... not urgent. Maybe close and make a seperate issue. My guess is because you need HLS option to work on safari)

m

**Comment by affan00** [comment]
done
