### ISSUE TITLE
Remove /dev page

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1150]

**Comment by marcoherbst** [comment]
We have /dev 
and /swagger

I notice that all pages (!) still give me console errors for the swagger dashboard. That's annoying. It's annoying that we're even loading that JS in all pages.

In the spirit of optimising our pages and reducing the amount of unnecessary JS we load and errors we produce, let's remove the /dev page and instead, in the navigation under Develop "Docs" have this open in a new window the "swagger" page.

Does that make sense?

Please tackle this task in the spirit of the higher goal of optimising our pages. There are bonus points if you manage to remove other non-used JS and solve the Google Maps console error at the same time.

**Comment by muneeb2542** [comment]
@marcoherbst the errors on each page due to swagger were the result of unused API explorer code.
We hid the API explorer but due the js file still being executed, there was errors and request on each page.I just removed all the unused code for it and the swagger requests on each page have stopped happening.

So I think it would be unnecessary to remove the dev page but if you still want it I can remove it altogether and redirect to swagger.

PS on dev we have information for API id and API key,if we remove the dev page where do you want the information to be represented?

**Comment by marcoherbst** [comment]
Good point re: ID & Key. Let's move them on to the Account Settings page .... then continue with the ticket as I asked for it.

Also, don't forget https://dash.evercam.io/v1/users/{id}/apps when you're cleaning up OAuth.

m

**Comment by muneeb2542** [comment]
@marcoherbst  I have removed the dev page and also removed all the unnecessary js files.The google maps error that we encounter is due to no API keys and they can be obtained only by registering our application with google cloud.So i left that and deployed the rest.

closing this.
