### ISSUE TITLE
Signup issues when user come using signup link from share-request email

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboard#1357]
For @affan00 
- [x]  Email overlap textbox label
- [x] User can edit email

For @muneeb2542 
- [x] User failed to auto login after complete signup procedure but user created successfully and can login from the login form.

**Comment by marcoherbst** [comment]
Re: User can edit email.

I see 2 options:

1. We continue with user cannot edit email, but we change the interface so that this is obvious. Currently it is not.

2. We change the functionality to allow a user to change their email. 

I consider option 2 to be problematic, and suggest you go for option 1.

**Comment by azharmalik3** [comment]
@marcoherbst I think we go with option 1.

**Comment by muneeb2542** [comment]
I am not able to replicate this error of user being able to auto login.I just created 4 new users and all of them were automatically redirected to the index page.So I am closing this issue but will keep an eye out if such error arises again.

**Comment by ijunaidfarooq** [comment]
This was mostly from evercam-media and have been fixed a long time ago!
