### ISSUE TITLE
Online Log Event should include text "after xx seconds / mins / days"

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1413]
Had this on camba, was nice.

Think carefully, is this a dash issue or a media issue or both.

**Comment by marcoherbst** [comment]
Moving this to a new issue and reiterating : If you want to implement this in Media, then I'd like to hear a good reason why. @azharmalik3 @muneeb2542  Otherwise, I see it as an issue for Affan in Dash

**Comment by muneeb2542** [comment]
@marcoherbst On Client side we would have to parse the whole table for each online event in logs and check for an offline event in it to calculate the duration between them.For example, if we have a record of 200 and there are 40 online events then for each online event the records below the online event would be parsed again and again and checked for an offline event.

So it would be time-consuming little and not a good practice.Plus if the last record is an online event then nothing could be shown with it because no data left to calculate it.That is why i think it would be better to do it from media.

**Comment by marcoherbst** [comment]
just so as not to lose the idea: https://github.com/evercam/evercam-media/issues/404

**Comment by marcoherbst** [comment]
I'm 90% sure this should be done client side rather than server side (the opposite of Muneeb's opinion), but ... I think you should confirm with Azhar and get his opinion. If (I dont think it will, but) there is a client side processing delay, then so long as it is asynchronous, it is still better than the alternative (a delay server side).

**Comment by azharmalik3** [comment]
Done.

**Comment by marcoherbst** [comment]
Good, but could you make the text "after 26 days, 1 hours, 36 mins, 33 seconds" in black (not green). tks.

**Comment by marcoherbst** [comment]
@affan00

**Comment by affan00** [comment]
It's done. Will be deployed on next working day.
