### ISSUE TITLE
Logs showing nothing for Sept...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1467]
This may be a media issue, but I'll start with @muneeb2542 

I shared the camera and then i looked at logs. I see nothing at all in Sept.

![image](https://cloud.githubusercontent.com/assets/5648894/18350947/1f793ffe-75d0-11e6-935d-f401bba5d225.png)

**Comment by muneeb2542** [comment]
@marcoherbst I have checked the logs for this camera for the month of September and it seems that for the first 8 days there are no logs but after the logs seemed fine.This is not due to the Dashboard but in fact, no information was sent for those 8 days that is why nothing was parsed.

So this issue is irrelevant to Dashboard.So closing this
