### ISSUE TITLE
Display camera response along with message on test snapshot.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboard#1474]

**Comment by marcoherbst** [comment]
Hmmm .... I fear you've lost track of this.

This issue came to life during work with Nain.
We saw that Dashboard correctly showed a "Device Busy" message on Test Snapshot.
Android did not.

That is what started the conversation .... I'm not sure where you're going with this issue, can you explain more:

a) current situation
b) your idea for how it should be

**Comment by azharmalik3** [comment]
It's not dashboard task. 

Closing now.
