### ISSUE TITLE
Cameras page does not refresh cameras status.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-dashboard#1513]
Cameras were offline (/cameras/ page).

Cameras came online (images updated) but status did not update (still offline).

**Comment by marcoherbst** [comment]
Before going ahead with this, please explain the method to be used. Research please a nice way of doing this.

**Comment by ijunaid8989** [comment]
According to evercam server: This work has already been done.

https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/util.ex#L72
There is a socket event as `broadcast_camera_status` and it's being sent to dashboard https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/snapshot/db_handler.ex#L99 when Evercam Server changes the status of camera, And it's also being received from dashboard as well, https://github.com/evercam/evercam-dashboard/blob/master/app/assets/javascripts/sidebar.js.coffee#L73

But it's not working, though: This thing is related to camera online offline logs, As In evercam server we are facing this issue that camera status logs are not being logged due to crash during the process. And this `camera-status-changed` event is being sent to dashboard during this process.

**Comment by ijunaid8989** [comment]
There was a bug in this method https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/snapshot/db_handler.ex#L97

Why Dashboard was not updating status:

while broadcasting to the dashboard , we were not sending the updated camera object for status. So when if the old status was offline, the newly sent status was offline as well. so the dashboard doesn't react on this, and vice-versa.

This is found during  testing for camera status update and fixed in https://github.com/evercam/evercam-server/pull/721

**Comment by marcoherbst** [comment]
@ijunaid8989 I'm also moving this to October just so that we clean up the issue. For dicussion.

**Comment by ijunaid8989** [comment]
I have fixed this already.. and its working now.
https://github.com/evercam/evercam-dashboard/issues/1513#issuecomment-302067836
