### ISSUE TITLE
Share performance issues

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1708]
From the screenshot, 2 bad things happened:

1. It was very slow (about 5 seconds, should be less than 1 second) after pressing send.
2. As a frustrated user, I double clicked and created 2 entries. This should not be possible.

![image](https://cloud.githubusercontent.com/assets/5648894/23914524/19fffba2-08de-11e7-9f9a-8884f1c4ab3a.png)

Good luck :)

**Comment by marcoherbst** [comment]
@ijunaid8989 if you felt ready for this task, it is one that I consider important, but I know there is too much on @azharmalik3 's todo list at the moment ... ?

**Comment by ijunaid8989** [comment]
I worked on improving camera share feature, And the only thing which could be improved was the search query for user, which we were first doing against username and email and now its only email, So instead of that change, I couldn't find anything or any solution for this, Single camera share take 1 sec max, As we have removed the wrapper between dash and server so ajax can directly contact the server, Its pretty much better than before, What we could do right now, for the 2nd point: (as confused user I clicked it twice), we can disable the button on the first click until we get the response from server (success or fail)..

@affan00 this is for you now to do that button enable and disabled.

**Comment by affan00** [comment]
It's done, Disabled button after user click on the share button.
