### ISSUE TITLE
Rails 5 Update

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#1916]
@affan00 can you?
Use this ticket to collect details of the obstacles.

**Comment by affan00** [comment]
Successfully updated to rails latest version(5.1.4).

- Removed gems that are not compatible with rails 5 i-e: Jazz_hands, quiet_assets.
- Fixed the 'before_filter' error that caused due to 'ie_iframe_cookies' gem, in order to fix this error there need to be some changes in this gem so I forked this gem and did the required changes and include this gem from my GitHub repository.
- There are some changes need to be made in "protected_attributes_continued" gem in order to make it compatible with rails 5, one GitHub user "westonganger" already did that changes so I used this gem from his GitHub.
- ActionController:: TestCase has changed, now we have to use keyword arguments over positional arguments. The keyword arguments accepted are params, session, flash, method, body and xhr. So, I fixed the failed Travis test by using keyword argument params.
- Added new gem 'rails-controller-testing'.
- There was an error "No such middleware to insert before: ActionDispatch:: Static" during precompile assets. This error is due to heroku_rails_deflate, Removing this gem fixed the error.

I tested dashboard after making these changes live and everything seems to be working fine now, so I am closing this issue.
