### ISSUE TITLE
snapmails - images not appearing on dashboard

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2123]
Often when I look in the dashboard at snapmails, it does not correctly load the images.

please try and find this and fix it.

i did ask before and you could not replicate it, but for me it happens 9 times out of 10 ... so try again on an existing user account with many snapmails

**Comment by affan00** [comment]
It's fixed now, The issue was sometimes in single snapmail the image container doesn't calculate its width and height that is why it shows 0 height for image container that causes image not to display, What I did is to calculate and set the height and width of the image container in case it's height is zero.
