### ISSUE TITLE
Snapmail images too large in email, need to be 100%

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2160]
I think this is true in Outlook client on mobile or low res devices.

**Comment by affan00** [comment]
we have already set snapmail image width to 100% so that it will appear according to width on all the devises and I have tested it on Gmail and outlook mail address on desktop chrome, ios mobile and it works fine, sometimes it shows larger image on outlook and it's due to outlook layout, so I am closing this issue.
