### ISSUE TITLE
Add Intercom Events

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2387]
Include:

- [ ] Pressing "Edit" button
- [ ] Edit > Share
- [ ] Edit > Download

**Comment by affan00** [comment]
It's done, I am closing this now. 
I've used events instead of custom_attribute to track event tracking in the intercom. We can see these tracking events details on the intercom in two places.
On the right column of the user intercom profile that contains the user event activities for the last 90 days.
![Screenshot from 2019-04-05 11-17-51](https://user-images.githubusercontent.com/14149453/55607150-d6153080-5794-11e9-9163-5c1c61c67133.png)

on the left column that contains the total counts of the events triggering. 
![Screenshot from 2019-04-05 11-18-05](https://user-images.githubusercontent.com/14149453/55607259-2db39c00-5795-11e9-9b9b-a3cd1ee0b1ac.png)
