### ISSUE TITLE
Tablet Mode: Not working well with Zoom (etc.) icons OR the Edit Image features

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#2449]
I'll share a video which shows the problems.

**Comment by affan00** [comment]
It's fixed now.
Used the double touch in order to achieve the zoom magnifier on touch devices (mobile/tab), and I've fixed the bug for edit image not working fine on touch devices.
NB: We are not using the edit image functionality for the recording widget because we have no edit image functionality for mobile applications for now.

I am closing this issue now.
