### ISSUE TITLE
Error on visiting admin dashboard when there are no cameras

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-dashboard#617]
![admin dashboard error](https://cloud.githubusercontent.com/assets/2011812/9122366/35e9b7fa-3ca6-11e5-909a-2881ebff0d54.png)

**Comment by marcoherbst** [comment]
Nice one. 

I'm not sure if it's relevant, but the intention is to remove Admin from evercam-dashboard entirely. Azhar is currently working on this and, if things go to plan, it should be live by the middle of next week. 

That will hopefully either mean this issue is solved or that it will become an issue on the evercam-admin repo.

One of the motivations behind doing this is to draw a clearer line between the dashboard app which uses the API .... and the admin app which will have direct DB access.

**Comment by marcoherbst** [comment]
We think this is solved due to move to admin area. Closing.
