### ISSUE TITLE
Improve recording schedule interface

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#639]
- [x] Remove status
- [x] Make the scheduler narrower
- [x] Move scheduler under the snapshots calendar
- [x] Make scheduler visible to users with read-only rights
- [x] Notify users who have read-only rights that they're unauthorized
- [x] Remove scheduler scroll bar and make it full height
- [x] Set the bar color to our blue
- [x] Change the time format to 24 hours
- [ ] Pop out scheduler for editing ?

**Comment by marcoherbst** [comment]
@mosic ... you ticked some things here, like "remove status" that aren't done. Just not deployed? 

And, I guess you can reduece the height to about 25%, and remove "Show / Hide Schedule"

Sorry if this was all done, I see some things deployed.

M

**Comment by mosic** [comment]
@marcoherbst Status is now removed, forgot to commit it.

Reducing height to 25% isn't possible if we want it to stay readable. I could increase the interval length to an hour and reduce the row height, which would decrease height to less than half.

**Comment by marcoherbst** [comment]
I attach a screenshot of what I currently see, which I think you will
agree, is a bit ridiculous. Is that what you see?

Things that occur to me:

+ you dont need text in the time blocks (the white text on blue). (they
currently say the time)
+ the font size on the rows could be reduced a lot.
+ remove the "show / hide schedule" text. (always show if schedule is
selected, otherwise dont)
+ reduce the wasted vertical white space.
+ if you did all of those things, I think you can reduce the vertical
height of that component to approx 1/4 of current size.
+ if you can't then we're back to using it as a pop-up, it's totally not
acceptable as it is or even at 50% of what it is.

M


.[image: Inline images 1]

On 25 August 2015 at 19:16, Miloš Mošić <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> Status is now removed,
> forgot to commit it.
>
> Reducing height to 25% isn't possible if we want it to stay readable. I
> could increase the interval length to an hour and reduce the row height,
> which would decrease height to less than half.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-dashboard/issues/639#issuecomment-134691313>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
I didn't say that it wasn't ridiculous :)

Image didn't get through, but I'm assuming it's the same as on my machine.

**Comment by marcoherbst** [comment]
Voila.

![screenshot-dash evercam io 2015-08-25 20-08-30](https://cloud.githubusercontent.com/assets/5648894/9477086/45e094dc-4b68-11e5-8576-d14834dd43b8.png)

**Comment by marcoherbst** [comment]
As we're also going to have some more stuff coming along, such as:

+ interval
+ retention time / (and Gb?) 

I suppose it's ok to not break your back optimising for it in this view.

We could just solve all our problems by having another view to deal with all settings. We can also transpose this calendar .... that would be nice (at least for desktop users).
m

**Comment by mosic** [comment]
I've deployed a change with all your suggestions implemented and as you can see, its at about 50+% of the original height.

If I change the interval to an hour, it would cut it in half and the sidebar would look decent. (5 minutes of work)

Or we can leave it as is and return to this after motion detection, frequency etc. are implemented.

**Comment by asimism** [comment]
Done and tested
