### ISSUE TITLE
The live view pop-up window scroll bars need some love. 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#643]
![screenshot 2015-08-25 17 38 44](https://cloud.githubusercontent.com/assets/5648894/9472981/40ae2db6-4b50-11e5-9ef0-fddbc639e8e3.png)

**Comment by marcoherbst** [comment]
... and, if it's possible to hide teh address bar, we may as well do that too.

**Comment by muneeb2542** [comment]
The live view pop-up window scroll bar has been removed and the address bar cannot be removed as this functionality is not allowed in modern browsers due to security reasons.
![screenshot from 2015-11-30 18-23-12](https://cloud.githubusercontent.com/assets/6482077/11472592/7b490d70-978f-11e5-99ba-98b9830dcf8e.png)
