### ISSUE TITLE
On an account with many cameras, I scroll down the list, choose a camera and the list refreshes. I'd rather it didn't.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#753]
... so that the left navigation stays the same and I can choose another camera without having to scroll down again.

**Comment by muneeb2542** [comment]
@marcoherbst 

We are using slimscroll gem which is outdated and does not give us an option to start from other than top or bottom and since we are using ajax call to populate data into the sidebar so it would be difficult and kind of a hassle to make a function to get the offset of the selected camera and even then it won't be effective because we aren't using cookies with this..i can make the scroll bar to star from bottom but it won't make much of a difference.

What i can do is find a suitable alternative for this slimscroll gem and then apply that but i would have to research that first and make a cleaning of the previous code, which could take a lot of time.So i am gonna just leave this issue alone for some time and focus on more important tasks.If that is ok with you?

**Comment by marcoherbst** [comment]
Good.

**Comment by marcoherbst** [comment]
@muneeb2542 I've sent this to @affan00 as it relates to another task I'm discussing with him. The best example I've seen of what would work is the Wordpress admin interface.

**Comment by affan00** [comment]
done
