### ISSUE TITLE
/recordings shows a broken image (sometimes) when a camera is offline.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboard#780]
![screenshot 2015-11-11 09 27 37](https://cloud.githubusercontent.com/assets/5648894/11087972/93a4cff0-8856-11e5-83bd-f04fab430ffb.png)

@mosic could you pick this one up? It's not top priority, but I think you are the most likely person to be able to offer the most joined up solution.

**Comment by mosic** [comment]
This turned out to be an issue with evercam-media, we would try to update the thumbnail even if the camera went offline. I fixed it just now, but the problem is still present in cameras that stayed offline.

We can fix it easily using a Rake task, I made an issue in evercam-api for it: https://github.com/evercam/evercam-api/issues/521

**Comment by mosic** [comment]
Done in https://github.com/evercam/evercam-api/issues/521.
