### ISSUE TITLE
Recording widget on mobile: The 'save' icon should disappear after clicking

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#840]
Currently when user click the 'save' icon on mobile, the snapshot gets saved but the save icon stays blue and doesn't disappear. This makes user feels the app/browser is freezing. It can be reproduced in both the Android app and Android browser.

It's not a critical issue but would be great if it can be improved :)

![screenshot_20151218-103752](https://cloud.githubusercontent.com/assets/5046761/11895089/9527fe12-a573-11e5-847e-19dcd33992b5.png)

**Comment by muneeb2542** [comment]
@liutingdu  The webview is using hover that is why it was acting weird.I have made changes so that when a person clicks on the save icon it disappears and the comes back.Plus the save icon will remain blue because of hover function but it will now have a transition time of 1 second,so you will know it's back.

**Comment by liutingdu** [comment]
:+1:
