### ISSUE TITLE
Live view should switch to jpeg if h264 url not found

### ISSUE THREAD

**Issue by faisal2472** [evercam/evercam-dashboard#854]

**Comment by marcoherbst** [comment]
Good stuff.

It's worth knowing that there are (I am pretty sure) cameras for whom the CORRECT RTSP URL is "/" .

I forget which ones, but they do exist.

So, your choices as I see them are:

1. Clean up the way we handle "null" data in RTSP path so that if we have entered "/" it is considered non null. (the best way)
2.  Treat "/" as a null path. (the quick way).

M

**Comment by muneeb2542** [comment]
Done
