### ISSUE TITLE
Index page has a memory leak

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-dashboard#976]
After the changes for https://github.com/evercam/evercam-dashboard/issues/953, if the index page is opened for a couple of minutes it steadily grows in memory and eventually crashes the tab/browser.

Nice resource for this problem: https://developers.google.com/web/tools/chrome-devtools/profile/memory-problems/memory-diagnosis

**Comment by muneeb2542** [comment]
@mosic  This issue was due to the function appending the src with rand.So each time the function ran rand was added again and again.Now i have fixed the code and it will only make change to to the thumbnail src provided from the camera helper.

I have also tested the code now by changing the interval time to 5 seconds instead of 60 and left the index for more than 20 min.Not one did it crash and each time the thumbnails were updated.

So i'm closing this issue now.
