### ISSUE TITLE
Cameras details work responsively (as a partial?)

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-dashboard#999]
Create widget for the Details tab that can be used in Android & iOS WebView https://github.com/evercam/evercam-play-android/issues/160

The embedded code could look similar with the cloud recording widget:
```
<html>
<body style='margin:0;padding:0;'>
  <div evercam="snapshot-navigator"></div>
  <script type="text/javascript" src="https://dashboard.evercam.io/snapshot.navigator.js?camera=hikdemo"></script>
</body>
</html>
```

The widget should inlude everything that is currently in Details page - view & edit camera details, camera model thumbnail, map, latest snapshot, remove camera etc.

**Comment by mosic** [comment]
This could be done without making a fullblown widget, by exposing the details partial as a separate page. 

The end result is the same from the Android app's point of view.

**Comment by marcoherbst** [comment]
@muneeb2542 , this is probably a task for you.

I think this is interesting, because possibly the same principle could be applied to sharing , logs, archives & future tabs that would allow us to easily add these functions to the Android & iOS apps.

I think @mosic has a picture in mind of how this might be done, if it's not clear to you how you'd like to tackle this (or how you'd like @affan00 to tackle it) then perhaps you'd liaise with Milos when the time comes. (Not urgent).

**Comment by muneeb2542** [comment]
The main functionality is done but the layout needs to be fixed,So I'm assigning the rest of the issue to @affan00 ,he will fix the layout and merge it with the pull request already created.

**Comment by affan00** [comment]
@muneeb2542  Fixed the interface. you can pull the relevant changes. it's done from my side.
![widget-info](https://cloud.githubusercontent.com/assets/14149453/14079617/8673fe6c-f518-11e5-83ab-0cd6cd1fcd9a.png)

**Comment by marcoherbst** [comment]
Closing this, we'll revisit it in the future.
